import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "../globals.css";
import { Providers } from "../Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main >
      {" "}
      <Providers>{children}</Providers>
    </main>
  );
}
